service: currency-alert

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: prod
  timeout: 3
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - ses:SendEmail

functions:
  check:
    handler: handler.run
    events:
      - schedule: rate(12 hours)
    reservedConcurrency: 1